### ISSUE TITLE
Stonecol and Stonecold are both common words?

### ISSUE THREAD

**Issue by aJetHorn** [danielmiessler/SecLists#100]
I find it hard to believe that Stonecol and Stonecold are, separately, among the 10k most commonly used words. Thoughts?

https://github.com/danielmiessler/SecLists/blob/master/Passwords/10k_most_common.txt

**Comment by Shifterovich** [comment]
Most used **pass**words, not _words_.

**Comment by aJetHorn** [comment]
Right. My understanding is that each entry in the word list is a password that has been observed to be among the 10k most commonly used passwords. To me, it seems likely that "Stonecol" was mistakenly added as a substring of "Stonecold" and then was ignored during filtering. It does not seem likely at all that a significant sample size of dumped passwords were found to have arbitrarily truncated the letter 'd' from "Stonecold".

**Comment by Shifterovich** [comment]
"Stonecold" makes more sense than "Stonecol", indeed, but there is also the possibility of "stonecol" being among the 10k most commonly used passwords due to the origin of this data. However, "stonecol" isn't a website, company, or anything else (it's literally nothing), so the substring mistake is more probable :P. Mistakes like that happen with big wordlists.

**Comment by aJetHorn** [comment]
Is the list sorted from most to least frequent? If so, I think it'd be safe to conclude that Stonecol's ranking 4000 places ahead of Stonecold suggests a substring error.

**Comment by Shifterovich** [comment]
This list is similar to the other lists like `10_million_password_list_top_1000000.txt` which are sorted for sure (since there are lists containing parts of the this list such as `top_100k.txt`, `top_1000.txt`, etc) and common sense suggests that `password` is a more common password than `zzzxxx`, so it seems like it's sorted the right way.

**Comment by aJetHorn** [comment]
Noticing it with Liverpoo and Liverpool too. I'll write a script later today and take a more detailed look at this. Might be worth sprucing it up.

**Comment by Shifterovich** [comment]
Good idea, although check whether it's just the last letter before writing the script.

**Comment by bomattin** [comment]
Looks like, with the two examples you've given, this may be a side effect of certain (very, very poor) systems imposing a MAXIMUM password length of 8 chars. I can think of one website offhand that used to do this.
