### ISSUE TITLE
[Question]: Can u guys pls add this password list

### ISSUE THREAD

**Issue by ElectroBoy10** [danielmiessler/SecLists#1048]
Here is the router :Rain
More specific :5G.rain_high_NT25

**Comment by ItsIgnacioPortal** [comment]
@ElectroBoy10 Are you refering to this router?
![rain-router](https://github.com/danielmiessler/SecLists/assets/46269721/366c2a5c-4817-4d14-af0c-ca890f9f206c)

If no, please share a link or a picture of the router.

**Comment by ElectroBoy10** [comment]
Jes that is the router

**Comment by molangning** [comment]
Do open a pr for the password
https://github.com/danielmiessler/SecLists/tree/master/Passwords/Default-Credentials/Routers

**Comment by ItsIgnacioPortal** [comment]
We already have wordlists for default usernames & passwords of huawei routers:
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/Default-Credentials/Routers/huawei_default-passwords.txt
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/Default-Credentials/Routers/huawei_default-users.txt

If the default password/user for that router is not in those wordlists, please comment it here so we can add it. Otherwise, I believe this issue can be closed @g0tmi1k

**Comment by g0tmi1k** [comment]
hey @ElectroBoy10 

please can you confirm if this is the default password, otherwise, will close.

**Comment by g0tmi1k** [comment]
Not heard anything - closing
