### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by elliot-holley** [danielmiessler/SecLists#129]
hello, I'm having trouble downloading this. whenever I click on 'download' it just keeps on loading. any advice?

**Comment by bl4de** [comment]
@elliot-holley 
Download and/or clone problems are not caused by repository itself, they are GitHub features, so I don't think Daniel will be able to resolve your problem :)

This is likely problem with your machine/firewall/network settings/user permissions/browser.
I just checked this and I downloaded repo without any problems (it's ~187MB zip file).

Did you try to clone it using Git client?
