### ISSUE TITLE
merged.txt.tar.gz no longer exists?

### ISSUE THREAD

**Issue by davidclarke-au** [danielmiessler/SecLists#172]
Hi, 

I'd love a copy of merged.txt.tar.gz but cannot see it listed anymore, do I need to check a previous ver?

I'd recommend if you call this out in your README specially that you should continue to list it.

Thanks in advance.

**Comment by g0tmi1k** [comment]
Looks like it was removed in 2016 ~ https://github.com/danielmiessler/SecLists/commit/9b8e66e6421a579dadae38fe3550be3967973f3a#diff-242a5d0dbb897928001a6ea309febe95

So its gonna be dated... If you still want a copy of it: https://github.com/danielmiessler/SecLists/blob/601038eb4ea18c97177b43a757286d3c8a815db8/Passwords/merged.txt.tar.gz

Fixed in #180
