### ISSUE TITLE
Seclist.git size.

### ISSUE THREAD

**Issue by squalldna** [danielmiessler/SecLists#415]
hi. im sorry. im on limited data. how big is the seclist complete file size? thank you.

**Comment by shoeper** [comment]
zip download currently is 351,8 MiB

cd SecLists
du -sh .git
529M	.git

**Comment by secenv** [comment]
It would be nice if the size of this repo could be reduced. After a simple git clone of this repo, the .git directory uses 782MB, almost a third of what the whole repo uses. Since it's mostly text files
Maybe the commit history could be deleted after a backup/mirror archive? Or maybe running git maintenance would be of help, as https://stackoverflow.com/a/2116892 seems to suggest?
