### ISSUE TITLE
error cloning repo in Windows

### ISSUE THREAD

**Issue by jacknaguib** [danielmiessler/SecLists#658]
![Screenshot 2021-09-28 171911](https://user-images.githubusercontent.com/35910536/135041471-8092ca55-f0d9-4903-8b5c-d3479f724300.png)

The error is due to invalid path Payloads/File-names/traversal/..::..:::;

**Comment by g0tmi1k** [comment]
Yup!
You may need to find a different way to download then ;)
Could try the zip out.

**Comment by PinkDev1** [comment]
The files wouldn't be able to exist anyway on a Windows system, and therefor contributing would be more complicated than it has to on Windows. I think it'd be better if those files were compressed into a zip with a valid filename on this repo.

**Comment by jarekczek** [comment]
Windows workaround:
After cloning the repo you have it locally, but `git reset --hard` fails, because of invalid filenames. So we need to commit removal of these files. They are already staged for removal, which can be done with `git commit -mremoval`. But this would commit removal of all. So:
- `git status` to see all the files staged for removal
- issue `git restore --staged xxx` for each file/directory that you want to retain (you may also prepare a batch using output of previous command)
- `git reset --hard`

I suggest to remove also Web-Shells, or the builtin defender will go crazy :)
