### ISSUE TITLE
Is there a thing that can make out 4-digit pin codes that are not in this list?

### ISSUE THREAD

**Issue by ArifOrcan** [danielmiessler/SecLists#684]
I wanted to use a secure lock for the game "Rust" so i wouldn't get code raided and other such stuff. Can anyone help ne out?

**Comment by PinkDev1** [comment]
This will probably go over your head but whathever.
You could try inspecting network traffic on-the-fly and modifying your lock pin from `[1,2,3,4]` to `["","","",""]` in the HTTP message that would be sent to the server otherwise. Therefor, only you would be able to unlock the door, using a hand-crafted program which sends this _null_ 4-pin code.

**Comment by g0tmi1k** [comment]
This issue is a little off topic @ArifOrca, as what you are asking for is not related to a list of values, but rather reverse engineering
