### ISSUE TITLE
Potential addition: Common WordPress Plugin Filepaths

### ISSUE THREAD

**Issue by cydave** [danielmiessler/SecLists#788]
I'm working on some WordPress plugin stuff and wondered if there's interest in adding a top list
of commonly encountered files in WordPress plugins (i.e. the part after the plugin slug ->` /wp-content/plugins/slug-slug/*`).

Check out the gist below, which includes the top 1000 filepaths of "all" plugins available on the WordPress marketplace:

* (without count) https://gist.github.com/cydave/dba4a3d14ecee2d3484b8768add0f039#file-top-wp-plugin-files-txt=
* https://gist.github.com/cydave/dba4a3d14ecee2d3484b8768add0f039#file-top-wp-plugin-files-with-counter-txt=

If there's any interest what so ever let me know, I can also provide a bigger list :)

**Comment by ItsIgnacioPortal** [comment]
Interesting project. The best usecase I can think of for these lists is for detecting if a plugin is installed in a wordpress instance. But most people would rather use a wordpress scanner like wpscan instead of "manually" scanning directories. Maybe the maintainers of wpscan could find a better use for your lists.
