### ISSUE TITLE
files flagged as malware

### ISSUE THREAD

**Issue by javixeneize** [danielmiessler/SecLists#79]
Hi

Virustotal flags some files like FUZZDB_cmdasp.aspx as malware

https://www.virustotal.com/en-gb/file/5f959f480a66a33d37d9a0ef6c8f7d0059625ca2a8ae9236b49b194733622655/analysis/1422380865/

Is that a known issue?

Thanks

**Comment by amuntner** [comment]
Yup, it's a backdoor.

This is documented in the FuzzDB readme:
https://github.com/fuzzdb-project/fuzzdb/blob/master/README.md

"Downloading this repository is likely to cause a false-positive alarm by your antivirus or antimalware software, the filepath should be whitelisted. There is nothing in FuzzDB that can harm your computer as-is, however it's not recommended to store these files on a server or other important system due to the risk of local file include attacks. "
