### ISSUE TITLE
[Question]: How to work at google

### ISSUE THREAD

**Issue by MarwanEhab255** [danielmiessler/SecLists#983]

**Comment by m0n0lit** [comment]
responsibly

**Comment by Bilao600** [comment]
Hi my friend. yeah ok I understand but since the last time I've only
written to you and then you don't answer me with I've already told you say
if you want I'll offer you a sum of $300. please answer me to discuss a
little better or to have a little more details on the Robot Lucky jet or
Aviator Predictor thank you

**Comment by g0tmi1k** [comment]
Closing to empty spam issue
